import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const geist = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${geist.className} text-foreground bg-gradient-to-b from-neutral-900 via-background to-neutral-950 min-h-screen max-w-dvw overflow-x-hidden`}
        >
          {children}
        </body>
      </Providers>
    </html>
  );
}
